# Generated by Django 3.1.4 on 2021-01-25 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staticpagesconfig', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqs',
            options={'verbose_name_plural': 'FAQs Config'},
        ),
    ]
