# Generated by Django 3.1.4 on 2020-12-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(blank=True, help_text='Top categories to be displayed...', to='category.Category')),
                ('content', models.ManyToManyField(help_text='Top n news/content...', to='content.Content')),
                ('library', models.ManyToManyField(help_text='Top n audibles...', to='content.Library')),
            ],
            options={
                'verbose_name_plural': 'Configure',
            },
        ),
    ]
