# Generated by Django 3.1.4 on 2020-12-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20201228_1444'),
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configure',
            name='category',
        ),
        migrations.RemoveField(
            model_name='configure',
            name='content',
        ),
        migrations.AddField(
            model_name='configure',
            name='articles',
            field=models.ManyToManyField(blank=True, help_text='Top articles to be displayed.', limit_choices_to={'active': True, 'sub_category__category__slug': 'articles'}, related_name='content_articles', to='content.Content'),
        ),
        migrations.AddField(
            model_name='configure',
            name='articles_section',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configure',
            name='blogs',
            field=models.ManyToManyField(blank=True, help_text='Top blogs to be displayed.', limit_choices_to={'active': True, 'sub_category__category__slug': 'blogs'}, related_name='blogs_articles', to='content.Content'),
        ),
        migrations.AddField(
            model_name='configure',
            name='blogs_section',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configure',
            name='library_section',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configure',
            name='news',
            field=models.ManyToManyField(blank=True, help_text='Top categories to be displayed...', limit_choices_to={'active': True, 'sub_category__category__slug': 'news'}, related_name='news_articles', to='content.Content'),
        ),
        migrations.AddField(
            model_name='configure',
            name='news_section',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configure',
            name='objects_count',
            field=models.IntegerField(default=10, help_text='The no. of objects in each section'),
        ),
        migrations.AlterField(
            model_name='configure',
            name='library',
            field=models.ManyToManyField(blank=True, help_text='Top n audibles...', limit_choices_to={'active': True}, to='content.Library'),
        ),
    ]
