# Generated by Django 3.1.4 on 2020-12-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20201228_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configure',
            name='articles_section',
            field=models.BooleanField(default=True, help_text='Show/Hide Articles Section on Home page'),
        ),
        migrations.AlterField(
            model_name='configure',
            name='blogs_section',
            field=models.BooleanField(default=True, help_text='Show/Hide blogs Section on Home page'),
        ),
        migrations.AlterField(
            model_name='configure',
            name='library_section',
            field=models.BooleanField(default=True, help_text='Show/Hide Library Section on Home page'),
        ),
        migrations.AlterField(
            model_name='configure',
            name='news_section',
            field=models.BooleanField(default=True, help_text='Show/Hide News Section on Home page'),
        ),
    ]
