# Generated by Django 3.1.4 on 2020-12-21 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0001_initial'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Status'},
        ),
        migrations.AddField(
            model_name='content',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='content',
            name='summary',
            field=models.TextField(blank=True, help_text='If left blank, first 200 characters             from content will be displayed as summary.', null=True),
        ),
        migrations.AddField(
            model_name='library',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='library',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='sub_category',
            field=models.ManyToManyField(blank=True, to='category.SubCategory'),
        ),
        migrations.AlterField(
            model_name='library',
            name='sub_category',
            field=models.ManyToManyField(blank=True, to='category.SubCategory'),
        ),
    ]
