# Generated by Django 3.1.4 on 2020-12-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20201221_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='summary_image',
            field=models.ImageField(blank=True, null=True, upload_to='content/images/'),
        ),
        migrations.AddField(
            model_name='library',
            name='summary_image',
            field=models.ImageField(blank=True, null=True, upload_to='content/images/'),
        ),
    ]
