# Generated by Django 3.1.4 on 2020-12-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20201228_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='slug',
            field=models.CharField(default='pending', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
