# Generated by Django 3.1.4 on 2020-12-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_content_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='filetype',
            field=models.CharField(default='mp3', help_text='file extension', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='library',
            name='size',
            field=models.FloatField(default=1, help_text='MB'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='library',
            name='title',
            field=models.CharField(help_text='Display name', max_length=200, unique=True),
        ),
    ]
