# Generated by Django 3.1.4 on 2020-12-30 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0007_auto_20201230_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='audio_file',
            field=models.FileField(help_text='Allowed type - .mp3, .wav, .ogg', upload_to='content/library'),
        ),
        migrations.AlterField(
            model_name='library',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
