# Generated by Django 3.1.4 on 2020-12-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20201230_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='summary',
            field=models.TextField(default='test', help_text='If left blank, first 200 characters             from content will be displayed as summary.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='library',
            name='summary',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
