# Generated by Django 3.1.4 on 2021-01-05 17:03

from django.db import migrations, models
import utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_auto_20210101_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='summary',
            field=models.TextField(help_text='Please enter a minimum of 180 characters', validators=[utils.utils.validate_summary_len]),
        ),
        migrations.AlterField(
            model_name='library',
            name='summary',
            field=models.TextField(help_text='Please enter a minimum of 180 characters', validators=[utils.utils.validate_summary_len]),
        ),
    ]
