# Generated by Django 3.1.4 on 2021-01-06 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0012_auto_20210106_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='approved_rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_rejected_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='library',
            name='approved_rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Content_approved_rejected_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
