# Generated by Django 3.1.4 on 2021-01-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_auto_20210106_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='watermark_image',
            field=models.ImageField(blank=True, null=True, upload_to='content/images/'),
        ),
        migrations.AddField(
            model_name='library',
            name='watermark_image',
            field=models.ImageField(blank=True, null=True, upload_to='content/images/'),
        ),
    ]
