# Generated by Django 3.1.4 on 2021-01-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_auto_20210106_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='album_name',
            field=models.CharField(default='Default Album', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='library',
            name='singer_name',
            field=models.CharField(default='Anonymous', max_length=100),
            preserve_default=False,
        ),
    ]
