# Generated by Django 3.1.4 on 2021-01-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_auto_20210113_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='duration',
            field=models.FloatField(default=0),
        ),
    ]
