# Generated by Django 3.1.4 on 2021-01-15 18:49

from django.db import migrations, models
import utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_auto_20210113_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='name',
            field=models.CharField(help_text='Write the name only in English Language', max_length=200, unique=True, validators=[utils.utils.validate_is_english]),
        ),
        migrations.AlterField(
            model_name='library',
            name='name',
            field=models.CharField(help_text='Write the name only in English Language', max_length=200, unique=True, validators=[utils.utils.validate_is_english]),
        ),
    ]
