# Generated by Django 3.1.4 on 2021-01-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_auto_20210115_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='summary_image',
            field=models.ImageField(default=1, upload_to='content/images/'),
            preserve_default=False,
        ),
    ]
