# Generated by Django 3.1.4 on 2021-01-26 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('myaccount', '0003_auto_20210115_1856'),
        ('reaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reaction',
            options={'verbose_name_plural': 'Likes & Comments'},
        ),
        migrations.AddField(
            model_name='reaction',
            name='reaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='self_fk', to='reaction.reaction'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ['content', 'library']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myaccount.userdetail', verbose_name='Posted By'),
        ),
    ]
