# Generated by Django 3.1.4 on 2020-12-26 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdetail',
            options={'verbose_name_plural': 'Actual User Account'},
        ),
    ]
