# Generated by Django 3.1.4 on 2021-01-15 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0002_auto_20201226_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdetail',
            options={'verbose_name_plural': 'End Users'},
        ),
    ]
